------------------------------------------------COMM001------------------------------------------------
INSERT INTO COMM001
(CODE,  CONTENT)
VALUES ('A001', 'ADMIN');

INSERT INTO COMM001
(CODE,  CONTENT)
VALUES ('A002', 'MANAGE');

INSERT INTO COMM001
(CODE,  CONTENT)
VALUES ('A004', 'seller');

INSERT INTO COMM001
(CODE,  CONTENT)
VALUES ('A003', 'USER');

INSERT INTO COMM001
(CODE,  CONTENT)
VALUES ('B001', '주문완료');

INSERT INTO COMM001
(CODE,  CONTENT)
VALUES ('B002', '결제완료');

INSERT INTO COMM001
(CODE,  CONTENT)
VALUES ('B003', '배송준비중');







------------------------------------------------USERS------------------------------------------------
INSERT INTO USERS 
(USER_NO,USER_ID,USER_PW,USER_NAME,SEX,BIRTH,EMAIL,PHONE_NO,USER_ZCODE,ADDR1,ADDR2,CREATEDATE,UPDATEDATE,LASTLOGIN,USER_USE,CART,CODE)
VALUES
(0,'admin','1234','관리자',0,'1993-10-25','admin@naver.com','010-0000-0000','0000','경기도','성남시',NOW(),NOW(),NOW(),1,'','A001');
----------------------------------------------PRODUCTS-----------------------------------------------
INSERT INTO PRODUCT (PRODUCT_NO, PRODUCT_ID, PRODUCT_NAME, PUBLISHER, PRODUCT_STATUS, PRODUCT_PRICE, CATEGORYS, QUANTITY, DETAIL, IMAGE, PRODUCT_RATING, SALES_QUANTITY, AUTHOR) VALUES ('PRODUCT_NO 1', 'PRODUCT_ID 1', 'PRODUCT_NAME 1', 'PUBLISHER 1', 'N', 1, 'N', 1, 'DETAIL 1', 'IMAGE 1', 1, 1, 'AUTHOR 1');
INSERT INTO PRODUCT (PRODUCT_NO, PRODUCT_ID, PRODUCT_NAME, PUBLISHER, PRODUCT_STATUS, PRODUCT_PRICE, CATEGORYS, QUANTITY, DETAIL, IMAGE, PRODUCT_RATING, SALES_QUANTITY, AUTHOR) VALUES ('PRODUCT_NO 2', 'PRODUCT_ID 2', 'PRODUCT_NAME 2', 'PUBLISHER 2', 'N', 2, 'N', 2, 'DETAIL 2', 'IMAGE 2', 2, 2, 'AUTHOR 2');
INSERT INTO PRODUCT (PRODUCT_NO, PRODUCT_ID, PRODUCT_NAME, PUBLISHER, PRODUCT_STATUS, PRODUCT_PRICE, CATEGORYS, QUANTITY, DETAIL, IMAGE, PRODUCT_RATING, SALES_QUANTITY, AUTHOR) VALUES ('PRODUCT_NO 3', 'PRODUCT_ID 3', 'PRODUCT_NAME 3', 'PUBLISHER 3', 'N', 3, 'N', 3, 'DETAIL 3', 'IMAGE 3', 3, 3, 'AUTHOR 3');

--------------------------------------------TRANSACTION----------------------------------------------
